### ISSUE TITLE
Connection Time-out

### ISSUE THREAD

**Issue by BlueTractorGuy** [jgamblin/CarHackingTools#3]
I am attempting to install but getting "ERROR 522: Origin Connection Time-out".  I have tried visiting the website directly and it is also down.  Is this a temporary outage or has it been permanently pulled down?

**Comment by jgamblin** [comment]
@BlueTractorGuy,

Sorry... I am in the middle of switching cloud providers for all of my sites.  I hope to have this back up by the end of the week.

Thanks,

Jerry

**Comment by BlueTractorGuy** [comment]
No worries.  Thank you for the quick reply.

**Comment by krusic22** [comment]
Any update on this?

**Comment by jgamblin** [comment]
Sorry, I lost this domain but am coming back to this project today.
