### ISSUE TITLE
Java 15 Error

### ISSUE THREAD

**Issue by Rossdavidson-ljmu** [jgamblin/CarHackingTools#6]
If there is anyone having an issue installing this on Ubuntu 20.04.2 and gets an error for a missing java15 file there is a simple fix. Open the toolinstall.sh file in an editor and change lines 70 + 71 to 'java16' instead of 'java15'. Hope this helps someone out!

**Comment by jgamblin** [comment]
Thanks for the heads up, I will rebuild this on 21.04 asap and update the install script! : )
